import enum


class URL(enum.Enum):
    KOMPAS = "https://news.kompas.com/news/sitemap.xml"
    DETIK = "https://news.detik.com/sitemap.xml"
    TRIBUN = "https://www.tribunnews.com/sitemap.xml"
    TEMPO = "https://www.tempo.co/sitemap.xml"
    KAPANLAGI = "https://www.kapanlagi.com/sitemap.xml"
    CNBC = "https://www.cnbcindonesia.com/sitemap.xml"
    CNN = "https://www.cnnindonesia.com/sitemap.xml"
    JPNN = "https://www.jpnn.com/sitemap.xml"
    REQNEWS = "https://www.reqnews.com/sitemap/latest.xml"
    PIKIRANRAKYAT = "https://www.pikiran-rakyat.com/sitemap-news.xml"
    SINDONEWS = "https://www.sindonews.com/sitemap.xml"
    ANTARANEWS = "https://en.antaranews.com/rss/spo.xml"
    GRIDID = "https://www.grid.id/sitemap/news/sitemap.xml"
    KONTAN = "https://www.kontan.co.id/sitemap.xml/"
    VIVA = "https://www.viva.co.id/sitemap.xml"
    BISNIS = "https://www.bisnis.com/sitemap.xml"
    BATAMPOS = "https://batampos.co.id/news-sitemap.xml"
    LIPUTAN6 = "https://www.liputan6.com/sitemap_news.xml"
    IDXCHANNEL = "https://www.idxchannel.com/sitemap.xml"
    MEDIAINDONESIA = "https://mediaindonesia.com/sitemap_news.xml"
    TIRTO = "https://tirto.id/s/sitemap-content.xml"
    INVESTORID = "https://investor.id/sitemap_news.xml"
    BERITASATU = "https://www.beritasatu.com/sitemap.xml"
    SUARA = ""
